async (page) => {
  page.setDefaultTimeout(10000); page.setDefaultNavigationTimeout(10000);
  const check=(value,message)=>{if(!value)throw new Error(message);};
  const results=[];
  await page.reload();
  if(await page.getByRole('textbox',{name:'Usuario',exact:true}).count()){
    await page.getByRole('textbox',{name:'Usuario',exact:true}).fill('demo-secretaria');
    await page.getByRole('textbox',{name:'Contraseña',exact:true}).fill('Demo-matricula-2026!');
    await page.getByRole('button',{name:'Ingresar'}).click();
  }
  await page.getByRole('heading',{name:'Expedientes',exact:true}).waitFor();
  await page.getByRole('combobox',{name:'Año escolar',exact:true}).selectOption('2026');
  if(await page.evaluate(()=>document.body.classList.contains('dark')))await page.getByRole('button',{name:'Cambiar tema claro u oscuro'}).click();
  await page.setViewportSize({width:1440,height:960});
  check(parseInt(await page.locator('.table-foot').textContent())>=400,'Conteo de expedientes');
  await page.getByRole('button',{name:'Siguiente',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('.table-foot')?.textContent.includes('página 2'));
  check((await page.locator('tbody tr').count())===25,'25 filas en segunda página');results.push('400 fichas, paginación y búsqueda');
  await page.getByRole('searchbox',{name:'Buscar estudiante'}).fill('Ejemplo 001');
  await page.waitForFunction(()=>document.querySelector('tbody')?.querySelectorAll('tr').length===1);
  await page.getByRole('button',{name:/Ejemplo 001 Sintético/}).click();
  await page.locator('#field-address').fill('Domicilio actualizado desde navegador');
  await page.getByRole('button',{name:'Guardar cambios',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('#save-state')?.textContent.startsWith('Guardado'));
  await page.getByRole('button',{name:'← Volver a expedientes'}).click();
  await page.getByRole('button',{name:/Ejemplo 001 Sintético/}).click();
  check((await page.locator('#field-address').inputValue())==='Domicilio actualizado desde navegador','Guardado no persistió');results.push('Guardado y reapertura persistente');
  await page.getByRole('button',{name:'← Volver a expedientes'}).click();
  await page.getByRole('button',{name:'+ Nueva matrícula'}).click();
  await page.getByRole('dialog').getByLabel('Nombres',{exact:true}).fill('Navegador sintético');
  await page.getByRole('dialog').getByLabel('Apellido paterno',{exact:true}).fill('QA Browser');
  await page.getByRole('dialog').getByRole('combobox',{name:'Identificación',exact:true}).selectOption('Otro');
  await page.getByRole('dialog').getByLabel('Identificador',{exact:true}).fill('QA-BROWSER-'+Date.now());
  await page.getByRole('dialog').getByRole('button',{name:'Continuar'}).click();
  await page.getByRole('heading',{name:/QA Browser.*Navegador sintético/}).waitFor();
  await page.locator('#field-address').fill('Borrador guardado por navegador');
  await page.waitForFunction(()=>document.querySelector('#save-state')?.textContent==='Guardado · revisión 2');results.push('Alta y autoguardado');
  await page.context().setOffline(true);
  await page.locator('#field-address').fill('Cambio durante fallo de red');
  await page.getByRole('button',{name:'Guardar cambios',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('#save-state')?.textContent.includes('No hay conexión'));
  check((await page.locator('#field-address').inputValue())==='Cambio durante fallo de red','Formulario perdido con red caída');
  await page.context().setOffline(false);
  await page.getByRole('button',{name:'Guardar cambios',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('#save-state')?.textContent==='Guardado · revisión 3');results.push('Fallo de red y recuperación sin perder formulario');
  await page.getByRole('button',{name:'Confirmar matrícula',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('.stat-line strong')?.textContent==='Matriculado');results.push('Confirmación');
  const [pdf]=await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:'Descargar ficha PDF'}).click()]);
  await pdf.saveAs('.local/browser-ficha-2026.pdf');check(!await pdf.failure(),'Descarga de PDF falló');results.push('PDF descargado');
  await page.getByRole('tab',{name:'Documentos',exact:true}).click();
  await page.getByRole('combobox',{name:'Tipo',exact:true}).selectOption('signed');
  await page.getByLabel('Archivo',{exact:true}).setInputFiles('.local/browser-ficha-2026.pdf');
  await page.getByRole('button',{name:'Guardar documento'}).click();
  await page.getByRole('button',{name:'Descargar',exact:true}).waitFor();results.push('Copia firmada guardada');
  await page.getByRole('button',{name:'Preparar otro año'}).click();
  await page.getByRole('dialog').getByRole('combobox',{name:'Curso y año'}).selectOption({label:'2027 · 1° Básico A'});
  await page.getByRole('dialog').getByRole('button',{name:'Continuar'}).click();
  await page.waitForFunction(()=>document.querySelector('#year-select')?.value==='2027');
  check((await page.locator('.stat-line strong').first().textContent())==='Borrador','Renovación no es borrador');results.push('Renovación al 2027');
  await page.getByRole('button',{name:'2026 · 1° Básico A',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('#year-select')?.value==='2026' && document.querySelector('.stat-line strong')?.textContent==='Matriculado');
  check((await page.locator('.stat-line strong').first().textContent())==='Matriculado','Renovación cerró año actual');
  await page.getByRole('button',{name:'Cambiar curso',exact:true}).click();
  await page.getByRole('dialog').getByRole('combobox',{name:'Nuevo curso'}).selectOption({label:'2° Básico A'});
  await page.getByRole('dialog').getByLabel('Motivo').fill('Traslado sintético por prueba integrada');
  await page.getByRole('dialog').getByRole('button',{name:'Continuar'}).click();
  await page.waitForFunction(()=>document.querySelector('.page-heading p:last-child')?.textContent.includes('2° Básico A'));
  await page.getByRole('button',{name:'Registrar retiro'}).click();
  await page.getByRole('dialog').getByLabel('Motivo').fill('Retiro sintético por prueba integrada');
  await page.getByRole('dialog').getByRole('button',{name:'Continuar'}).click();
  await page.waitForFunction(()=>document.querySelector('.stat-line strong')?.textContent==='Retirado');results.push('Traslado y retiro con historial');
  await page.getByRole('tab',{name:'Historial',exact:true}).click();check((await page.locator('.timeline').textContent()).includes('Retiro registrado'),'No apareció historial');
  await page.getByRole('button',{name:'Expedientes',exact:true}).click();
  await page.getByRole('searchbox').fill('');
  await page.waitForFunction(()=>document.querySelector('tbody')?.querySelectorAll('tr').length===25);
  await page.screenshot({path:'.local/browser-desktop-light.png'});
  await page.getByRole('button',{name:'Cambiar tema claro u oscuro'}).click();
  check(await page.evaluate(()=>document.body.classList.contains('dark')),'Tema oscuro');await page.screenshot({path:'.local/browser-desktop-dark.png'});
  await page.getByRole('button',{name:'Cambiar tema claro u oscuro'}).click();
  for(const width of [320,375,414,768]){await page.setViewportSize({width,height:844});const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);check(!overflow,'Desborde horizontal '+width);await page.screenshot({path:'.local/browser-mobile-'+width+'.png'});}
  results.push('Diseño claro/oscuro y 320/375/414/768 px');
  await page.setViewportSize({width:1440,height:960});console.log(JSON.stringify({passed:results}));return {passed:results};
}
