import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync,mkdirSync,readFileSync,writeFileSync,readdirSync } from 'node:fs';
import { join } from 'node:path';
import { createApp } from '../src/server.mjs';
import { openStore } from '../src/store.mjs';
import { restoreBackup } from '../src/backup.mjs';
import { seedDemo,demoPassword } from '../scripts/seed-demo.mjs';
import { createFichaPdf } from '../src/pdf.mjs';
test('Aceptación integrada con servidor y persistencia aislados',async t=>{
  mkdirSync('.local',{recursive:true});const directory=mkdtempSync(join('.local','api-test-')),app=await createApp({directory,demo:true});const data=await seedDemo(app.store,app.svc,400),address=await app.listen(0),base=`http://127.0.0.1:${address.port}`;t.after(()=>app.close());
  const login=async username=>{const r=await fetch(base+'/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,password:demoPassword})});assert.equal(r.status,200);const json=await r.json();return {cookie:r.headers.get('set-cookie').split(';')[0],csrf:json.csrf};};
  const admin=await login('demo-secretaria'),teacher=await login('demo-profesor'),reader=await login('demo-lector'),none=await login('demo-sin-cursos');
  const request=async(session,path,method='GET',body)=>{const r=await fetch(base+path,{method,headers:{Cookie:session.cookie,'X-CSRF-Token':session.csrf,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});return {status:r.status,data:r.headers.get('content-type')?.startsWith('application/json')?await r.json():Buffer.from(await r.arrayBuffer())};};
  let record=data.records[0],signedId,pdfBytes,backupBytes;
  await t.test('400 expedientes, búsqueda por nombre e identificador, paginación sin repeticiones',async()=>{
    const first=await request(admin,'/api/records?year=2026&page=1&pageSize=25'),second=await request(admin,'/api/records?year=2026&page=2&pageSize=25');assert.equal(first.data.total,400);assert.equal(first.data.items.length,25);assert(!second.data.items.some(x=>first.data.items.some(y=>x.id===y.id)));assert.equal((await request(admin,'/api/records?q=Ejemplo%20001')).data.total,1);assert.equal((await request(admin,'/api/records?q=DEMO001')).data.total,1);assert.equal((await request(admin,'/api/records?q=%25')).data.total,0);
  });
  await t.test('Permisos por curso y antecedentes reservados aplicados en servidor',async()=>{
    const allowed=await request(teacher,'/api/records/'+record.id);assert.equal(allowed.status,200);assert(!Object.hasOwn(allowed.data.data,'allergies'));assert.equal((await request(teacher,'/api/records/'+data.records[1].id)).status,403);assert.equal((await request(none,'/api/records')).data.total,0);assert.equal((await request(none,'/api/records/'+record.id)).status,403);assert.equal((await request(teacher,'/api/records/'+record.id,'PATCH',{version:1,data:{allergies:'ataque'}})).status,403);assert.equal((await request(reader,'/api/records/'+data.records[1].id,'PATCH',{version:2,data:{address:'sin permiso'}})).status,403);assert.equal((await request(teacher,'/api/audit')).status,403);
  });
  await t.test('Alta, borrador recuperable, identificación duplicada y validación de RUN',async()=>{
    const input={year:2026,courseId:data.courses[0].id,data:{names:'Nueva de prueba',surname:'Sintética',identifierType:'Otro',identifier:'TEST-NEW'}};const created=await request(admin,'/api/records','POST',input);assert.equal(created.status,201);assert.equal(created.data.status,'draft');assert.equal((await request(admin,'/api/records/'+created.data.id)).data.data.names,'Nueva de prueba');assert.equal((await request(admin,'/api/records','POST',input)).status,409);assert.equal((await request(admin,'/api/records','POST',{...input,data:{...input.data,identifierType:'RUN',identifier:'12345678-0'}})).status,400);
  });
  await t.test('Guardado del profesor no borra datos reservados y queda nueva revisión',async()=>{
    const saved=await request(teacher,'/api/records/'+record.id,'PATCH',{version:record.version,data:{address:'Domicilio sintético actualizado'}});assert.equal(saved.status,200);record={...record,...saved.data};const reopened=await request(admin,'/api/records/'+record.id);assert.equal(reopened.data.data.allergies,'ANTECEDENTE-SINTETICO-RESERVADO');assert.equal(reopened.data.data.address,'Domicilio sintético actualizado');const previous=await request(admin,`/api/records/${record.id}/revisions?version=1`);assert.equal(previous.data.data.address,'Domicilio ficticio');
  });
  await t.test('Edición simultánea: solo una escritura gana; conflicto explícito',async()=>{
    const responses=await Promise.all(['A','B'].map(v=>request(admin,'/api/records/'+record.id,'PATCH',{version:record.version,data:{observations:'Edición simultánea '+v}})));assert.deepEqual(responses.map(x=>x.status).sort(),[200,409]);assert.equal(responses.find(x=>x.status===409).data.code,'VERSION_CONFLICT');record={...record,...responses.find(x=>x.status===200).data};
  });
  await t.test('Autorizaciones independientes con fecha/responsable/versión y validación de fechas',async()=>{
    const path='/api/records/'+record.id;assert.equal((await request(admin,path,'PATCH',{version:record.version,data:{imagesDecision:'Sí'}})).status,400);assert.equal((await request(admin,path,'PATCH',{version:record.version,data:{birthDate:'2026-02-30'}})).status,400);const r=await request(admin,path,'PATCH',{version:record.version,data:{imagesDecision:'No',imagesDate:'2026-10-05',imagesResponsible:'Apoderado sintético',imagesVersion:'referencia-1',outingsDecision:'Sí',outingsDate:'2026-10-05',outingsResponsible:'Apoderado sintético',outingsVersion:'referencia-1',religionDecision:'No opto',religionDate:'2026-10-05',religionResponsible:'Apoderado sintético',religionVersion:'referencia-1'}});assert.equal(r.status,200);record={...record,...r.data};
  });
  await t.test('Confirmación, traslado y preparación anual conservan el año actual',async()=>{
    let r=await request(admin,`/api/records/${record.id}/actions`,'POST',{version:record.version,action:'enroll'});assert.equal(r.status,200);record={...record,...r.data};r=await request(admin,`/api/records/${record.id}/actions`,'POST',{version:record.version,action:'transfer',courseId:data.courses[1].id,reason:'Organización de prueba',date:'2026-10-05'});assert.equal(r.status,200);record={...record,...r.data};assert.equal((await request(teacher,'/api/records/'+record.id)).status,403);const renewal=await request(admin,`/api/records/${record.id}/renew`,'POST',{version:record.version,courseId:data.courses[8].id});assert.equal(renewal.status,201);assert.equal(renewal.data.year,2027);assert.equal(renewal.data.status,'draft');assert.equal(renewal.data.data.imagesDecision,undefined);assert.equal(renewal.data.data.allergies,'ANTECEDENTE-SINTETICO-RESERVADO');assert.equal((await request(admin,'/api/records/'+record.id)).data.status,'enrolled');assert.equal((await request(admin,`/api/records/${record.id}/renew`,'POST',{version:record.version,courseId:data.courses[8].id})).status,409);
  });
  await t.test('Plantillas con versiones; campos nuevos no alteran fichas anteriores',async()=>{
    const meta=(await request(admin,'/api/meta')).data,template=meta.templates[0];const created=await request(admin,'/api/templates','POST',{name:'Versión sintética de prueba',fields:[...template.fields,{key:'extraTest',label:'Pregunta de prueba',section:'adicionales',type:'text',sensitive:true}]});assert.equal(created.status,201);assert.equal((await request(admin,'/api/records/'+record.id)).data.templateId,1);assert.equal((await request(admin,'/api/templates','POST',{name:'Cambio no revisado',fields:template.fields.slice(1)})).status,400);
  });
  await t.test('PDF real, adjunto firmado versionado, permisos, integridad y auditoría de descarga',async()=>{
    const result=await request(admin,`/api/records/${record.id}/pdf`);assert.equal(result.status,200);pdfBytes=result.data;assert.equal(pdfBytes.subarray(0,5).toString(),'%PDF-');writeFileSync(join(directory,'ficha-2026.pdf'),pdfBytes);const uploaded=await request(admin,`/api/records/${record.id}/attachments`,'POST',{version:record.version,kind:'signed',name:'firma-sintetica.pdf',content:pdfBytes.toString('base64')});assert.equal(uploaded.status,201);signedId=uploaded.data.id;record.version=uploaded.data.version;assert.equal((await request(reader,'/api/attachments/'+signedId)).status,403);const downloaded=await request(admin,'/api/attachments/'+signedId);assert.deepEqual(downloaded.data,pdfBytes);assert.equal((await request(admin,`/api/records/${record.id}/attachments`,'POST',{version:1,kind:'signed',name:'otro.pdf',content:pdfBytes.toString('base64')})).status,409);
  });
  await t.test('Retiro con motivo y pasado protegido',async()=>{
    assert.equal((await request(admin,`/api/records/${record.id}/actions`,'POST',{version:record.version,action:'withdraw',reason:''})).status,400);const r=await request(admin,`/api/records/${record.id}/actions`,'POST',{version:record.version,action:'withdraw',reason:'Retiro sintético para prueba',date:'2026-10-05'});assert.equal(r.status,200);record={...record,...r.data};assert.equal((await request(admin,'/api/records/'+record.id,'PATCH',{version:record.version,data:{address:'cambio indebido'}})).status,409);assert.equal((await request(admin,`/api/records/${record.id}/pdf`)).status,200);
  });
  await t.test('Importación con procedencia, duplicados y aplicación atómica de filas revisadas',async()=>{
    const row={year:2026,courseId:data.courses[0].id,origin:'padron-sintetico',originId:'origen-001',data:{names:'Importado de prueba',surname:'Sintético',identifierType:'Otro',identifier:'IMPORT-001'}};const repeated=await request(admin,'/api/import/preview','POST',{rows:[row,row]});assert.equal(repeated.data.canImport,false);const preview=await request(admin,'/api/import/preview','POST',{rows:[row]});assert.equal(preview.data.canImport,true);assert.equal((await request(admin,'/api/import/commit','POST',{rows:[row],ticket:'incorrecto'})).status,409);const applied=await request(admin,'/api/import/commit','POST',{rows:[row],ticket:preview.data.ticket});assert.equal(applied.status,201);assert.equal(applied.data.count,1);assert.equal((await request(admin,'/api/import/preview','POST',{rows:[row]})).data.canImport,false);assert.equal((await app.store.db.prepare('SELECT origin_id FROM students WHERE origin=?').get(row.origin)).origin_id,row.originId);
  });
  await t.test('Exportación de curso, CSRF, sesiones y ausencia de exposición accidental',async()=>{
    const exported=await request(teacher,'/api/export?course='+data.courses[0].id);assert.equal(exported.status,200);assert(!exported.data.toString().includes('ANTECEDENTE-SINTETICO-RESERVADO'));assert.equal((await request(teacher,'/api/export?course='+data.courses[1].id)).status,403);const response=await fetch(base+'/api/courses',{method:'POST',headers:{Cookie:admin.cookie,'Content-Type':'application/json'},body:JSON.stringify({year:2028,name:'Sin CSRF'})});assert.equal(response.status,403);assert.equal((await fetch(base+'/../src/store.mjs')).status,404);assert.equal((await fetch(base+'/api/records')).status,401);assert.equal((await fetch(base+'/api/records',{headers:{Origin:'http://sitio-ajeno.invalid',Cookie:admin.cookie}})).status,403);
  });
  await t.test('Auditoría protegida, cambios y consultas/descargas sin secretos ni documentos completos',async()=>{
    const all=await app.store.db.prepare('SELECT * FROM audit').all(),serialized=JSON.stringify(all);assert(all.some(x=>x.action==='record.edit'));assert(all.some(x=>x.action==='record.read'));assert(all.some(x=>x.action==='pdf.download'));assert(all.some(x=>x.action==='document.download'));assert(all.some(x=>x.action==='request.conflict'));assert(!serialized.includes(demoPassword));assert(!serialized.includes('ANTECEDENTE-SINTETICO-RESERVADO'));assert(!serialized.includes(pdfBytes.toString('base64')));await assert.rejects(()=>app.store.db.exec('DELETE FROM audit'));await assert.rejects(()=>app.store.db.exec('UPDATE audit SET action="alterado"'));assert(await app.store.verifyAudit());const rows=(await request(admin,'/api/audit')).data;assert(rows.integrity);
  });
  await t.test('Respaldo cifrado y restauración de base, adjuntos e historial en carpeta nueva',async()=>{
    const result=await request(admin,'/api/backup','POST',{password:'Clave-sintetica-respaldo-2026!'});assert.equal(result.status,200);backupBytes=result.data;assert(!backupBytes.includes(Buffer.from('ANTECEDENTE-SINTETICO-RESERVADO')));assert.throws(()=>restoreBackup(backupBytes,'incorrecta',join(directory,'restore-bad')));const restored=restoreBackup(backupBytes,'Clave-sintetica-respaldo-2026!',join(directory,'restored'));assert.equal(restored.records,403);assert.equal(restored.attachments,1);assert.throws(()=>restoreBackup(backupBytes,'Clave-sintetica-respaldo-2026!',restored.dir));const s=openStore(restored.dir);try{assert(s.verifyAudit());assert.equal(s.db.prepare('SELECT count(*) AS n FROM sessions').get().n,0);assert.equal(s.db.prepare('SELECT status FROM records WHERE id=?').get(record.id).status,'withdrawn');assert.equal(JSON.parse(s.unseal(s.db.prepare('SELECT data FROM records WHERE id=?').get(record.id).data)).allergies,'ANTECEDENTE-SINTETICO-RESERVADO');}finally{s.close();}
  });
  await t.test('Reapertura en otro proceso lógico conserva fichas y auditoría',()=>{
    const second=openStore(directory);try{assert.equal(second.db.prepare('SELECT count(*) AS n FROM records').get().n,403);assert(second.verifyAudit());assert(readdirSync(join(directory,'attachments')).every(x=>x.endsWith('.enc')));const raw=readFileSync(join(directory,'matricula.sqlite'));assert(!raw.includes(Buffer.from('ANTECEDENTE-SINTETICO-RESERVADO')));}finally{second.close();}
  });
  await t.test('PDF con un antecedente largo conserva flujo entre páginas y numeración sin páginas vacías',async()=>{
    const stress={...record,events:[],data:{...record.data,observations:('Antecedente sintético largo para revisar salto de página. '.repeat(68))+'FIN DE ANTECEDENTE'}};
    const pdf=await createFichaPdf(stress,await app.svc.fieldsFor(1),data.courses[1],{name:'Prueba de texto largo'});const pages=[...pdf.toString('latin1').matchAll(/\/Type \/Page\b/g)].length;assert(pages>=8&&pages<=12);writeFileSync(join(directory,'ficha-stress.pdf'),pdf);
  });
  console.log('Evidencia sintética PDF:',join(directory,'ficha-2026.pdf'));
});
