const f = (key, label, section, type = 'text', sensitive = false, options) => ({ key, label, section, type, sensitive, ...(options ? { options } : {}) });
const yesNo = ['Sí', 'No', 'Pendiente'];
export const baseFields = [
  f('surname','Apellido paterno','identificacion'), f('secondSurname','Apellido materno','identificacion'), f('names','Nombres','identificacion'),
  f('identifierType','Tipo de identificación','identificacion','select',false,['RUN','IPE','Pasaporte','Otro','Provisional']), f('identifier','Identificador','identificacion'),
  f('birthDate','Fecha de nacimiento','identificacion','date'), f('birthPlace','Lugar de nacimiento','identificacion'), f('email','Correo del estudiante','identificacion','email'),
  f('address','Domicilio','identificacion'), f('addressChange','Cambio de domicilio','identificacion'),
  f('indigenous','Descendencia indígena','reservados','select',true,yesNo), f('indigenousDetail','Pueblo o descendencia indicada','reservados','text',true),
  f('emergencyPhone','Teléfono de emergencia','contactos','tel'), f('emergencyName','A quién se avisa','contactos'),
  ...['father','mother'].flatMap(p => [f(p+'Name',p==='father'?'Nombre del padre':'Nombre de la madre','padres'), f(p+'BirthDate','Fecha de nacimiento','padres','date'), f(p+'Alive','Vive','reservados','select',true,yesNo), f(p+'Identifier','Identificador','padres'), f(p+'Nationality','Nacionalidad','padres'), f(p+'Occupation','Ocupación','social','text',true), f(p+'Phone','Teléfono','padres','tel'), f(p+'Workplace','Lugar de trabajo','social','text',true), f(p+'Income','Ingreso','social','text',true), f(p+'Address','Domicilio','padres'), f(p+'Education','Escolaridad','social','text',true)]),
  f('parentsMaritalStatus','Situación civil de los padres','social','text',true),
  ...['guardian','alternate'].flatMap(p => [f(p+'Name',p==='guardian'?'Nombre del apoderado':'Nombre del apoderado suplente','apoderados'), f(p+'Identifier','Identificador','apoderados'), f(p+'Nationality','Nacionalidad','apoderados'), f(p+'BirthDate','Fecha de nacimiento','apoderados','date'), f(p+'Relationship','Parentesco','apoderados'), f(p+'Address','Dirección','apoderados'), f(p+'Phone','Teléfono','apoderados','tel'), f(p+'Email','Correo','apoderados','email'), f(p+'Education','Escolaridad','social','text',true), f(p+'Employment','Situación laboral','social','text',true), f(p+'Income','Ingreso','social','text',true), f(p+'Occupation','Ocupación','social','text',true)]),
  f('repeat','Repitente','matricula','select',false,yesNo), f('previousSchool','Procedencia escolar','matricula'), f('enrollmentNumber','Número de matrícula','matricula'), f('registryNumber','Registro o expediente','matricula'), f('receipt','Recibo de matrícula','matricula'), f('enrollmentDate','Fecha de matrícula','matricula','date'), f('fee','Valor matrícula declarado (no condiciona matrícula)','matricula'), f('gradeAverage','Promedio de notas','matricula'),
  f('pei','Constancia de información del PEI','constancias','select',false,yesNo), f('rules','Constancia de información de convivencia y evaluación','constancias','select',false,yesNo), f('pme','Constancia de información del PME','constancias','select',false,yesNo), f('inclusion','Constancia de información Ley 21.545','constancias','select',false,yesNo),
  f('protectionMeasures','Cautelares de protección','judicial','textarea',true), f('legalProhibitions','Otras prohibiciones documentadas','judicial','textarea',true),
  f('childrenCount','Total de hijos de la familia','social','text',true), f('childOrder','Lugar del estudiante en la familia','social','text',true), f('householdRelationships','Personas con las que vive y vínculo','social','textarea',true),
  f('housingTenure','Tenencia de vivienda','social','select',true,['Propia','Arrendada','Allegada','Usufructuario','Otra']), f('housingType','Tipo de vivienda','social','select',true,['Casa','Departamento','Mediagua','Pieza','Otra']), f('construction','Construcción','social','select',true,['Concreto','Madera','Albañilería','Mixta','Otra']),
  f('bedrooms','Número de dormitorios','social','text',true), f('beds','Número de camas','social','text',true), f('sharedBedroom','Dormitorio compartido','social','select',true,yesNo), f('electricity','Luz','social','select',true,['Eléctrica','Vela','Parafina','Otra']), f('water','Agua','social','select',true,['Potable','Pozo','Vertiente','Acarreo','Otra']), f('sewage','Eliminación de aguas','social','select',true,['Alcantarillado','Pozo negro','Fosa séptica','Campo abierto','Otra']), f('benefits','Beneficios o programas de apoyo','social','textarea',true), f('householdRegistry','Registro Social de Hogares','social','text',true),
  f('treatments','Enfermedades en tratamiento','salud','textarea',true), f('treatmentYear','Año del tratamiento','salud','text',true), f('visualImpairment','Antecedentes visuales','salud','text',true), f('motorImpairment','Antecedentes motores','salud','text',true), f('otherImpairment','Otros antecedentes físicos','salud','textarea',true), f('bloodGroup','Grupo sanguíneo','salud','text',true), f('healthSystem','Sistema de salud y tramo','salud','text',true), f('learningNeeds','Antecedentes de aprendizaje','salud','textarea',true), f('healthInsurance','Seguro de salud','salud','select',true,yesNo), f('insuranceName','Nombre del seguro','salud','text',true), f('insurancePhone','Teléfono del seguro','salud','tel',true), f('allergies','Alergias','salud','textarea',true),
  ...['religion','images','outings'].flatMap(p=>[f(p+'Decision',p==='religion'?'Preferencia de clases de religión':p==='images'?'Autorización de difusión de imágenes y audio':'Autorización anual de salidas pedagógicas','autorizaciones','select',p==='religion',p==='religion'?['Católica','Evangélica','Otra','No opto','Pendiente']:['Sí','No','Pendiente']),f(p+'Detail','Detalle o alcance informado','autorizaciones','textarea',p==='religion'),f(p+'Date','Fecha de decisión','autorizaciones','date',p==='religion'),f(p+'Responsible','Apoderado o tutor que declara','autorizaciones','text',p==='religion'),f(p+'Version','Versión del texto informado','autorizaciones','text',p==='religion')]),
  f('birthCertificate','Documento identificatorio recibido','documentos','select',false,yesNo), f('studyCertificate','Certificado de estudios recibido','documentos','select',false,yesNo), f('personalityReport','Informe de personalidad (no requisito de matrícula)','documentos','select',true,yesNo),
  f('officer','Funcionario que registra la matrícula','matricula'), f('observations','Observaciones administrativas','matricula','textarea'), f('withdrawalDocuments','Documentación retirada y otros informes','retiro','textarea',true), f('withdrawalResponsible','Apoderado que realiza el retiro','retiro'), f('withdrawalOfficer','Funcionario que realiza el retiro','retiro')
];
export const sections = { identificacion:'Identificación', contactos:'Emergencia', apoderados:'Apoderados', padres:'Padres', matricula:'Matrícula anual', constancias:'Constancias', autorizaciones:'Autorizaciones', documentos:'Documentos', reservados:'Otros antecedentes reservados', social:'Apoyo social', salud:'Salud', judicial:'Antecedentes judiciales', retiro:'Retiro', adicionales:'Preguntas adicionales' };
export const permissions = ['read','write','enroll','sensitive','documents','export','audit','admin','import','backup'];
export const permissionLabels = {read:'Consultar fichas',write:'Editar fichas',enroll:'Gestionar matrícula y años',sensitive:'Ver y editar antecedentes reservados',documents:'Adjuntar y descargar documentos',export:'Exportar fichas y nóminas',audit:'Consultar auditoría',admin:'Administrar cuentas y plantillas',import:'Importar padrón',backup:'Generar respaldos'};
export function displayLabel(field){const person=[['father','padre'],['mother','madre'],['guardian','apoderado'],['alternate','suplente']].find(([prefix])=>field.key.startsWith(prefix));return person&&!field.key.endsWith('Name')?`${field.label} (${person[1]})`:field.label;}
export function ageAtSchoolCutoff(birthDate,year){if(!/^\d{4}-\d{2}-\d{2}$/.test(birthDate||''))return '';const [y,m,d]=birthDate.split('-').map(Number),age=year-y-((m>3||(m===3&&d>30))?1:0);return age>=0&&age<100?String(age):'';}
export function normalizeIdentifier(value){ return String(value||'').normalize('NFKC').replace(/[.\s-]/g,'').toUpperCase(); }
export function validateIdentifier(type,value){
  if(type!=='RUN') return true;
  const clean=normalizeIdentifier(value);
  if(!/^\d{7,8}[0-9K]$/.test(clean)) return false;
  let sum=0,m=2; for(const n of clean.slice(0,-1).split('').reverse()){ sum+=Number(n)*m; m=m===7?2:m+1; }
  const v=11-sum%11; return clean.at(-1)===(v===11?'0':v===10?'K':String(v));
}
export function validateFields(fields){
  if(!Array.isArray(fields)||fields.length<baseFields.length||fields.length>180) throw new Error('Conserve la referencia y agregue hasta 180 campos.');
  for(const field of baseFields){ const match=fields.find(x=>x.key===field.key); if(!match||JSON.stringify(match)!==JSON.stringify(field)) throw new Error('Los campos de referencia se conservan en esta versión.'); }
  const keys=new Set(); for(const x of fields){
    if(!/^[a-zA-Z][a-zA-Z0-9]{1,60}$/.test(x.key)||keys.has(x.key)||typeof x.label!=='string'||!x.label.trim()||x.label.length>120||!Object.hasOwn(sections,x.section)||!['text','textarea','date','email','tel','select'].includes(x.type)||typeof x.sensitive!=='boolean') throw new Error('Campo adicional inválido.');
    if(x.type==='select'&&(!Array.isArray(x.options)||!x.options.length||x.options.length>30||x.options.some(o=>typeof o!=='string'||o.length>120))) throw new Error('Opciones inválidas.'); keys.add(x.key);
  }
  return fields;
}
