import { randomUUID } from 'node:crypto';
import { permissions, normalizeIdentifier, validateIdentifier, validateFields } from './fields.mjs';
import { hashPassword } from './store.mjs';

export class HttpError extends Error { constructor(status, message, code = '') { super(message); this.status = status; this.code = code; } }
export const fail = (status, message, code) => { throw new HttpError(status, message, code); };

export function createService(store) {
  const { db, seal, unseal, audit, transaction, mac } = store;
  const now = () => new Date().toISOString();
  const decodeUser = row => row && ({ ...row, permissions: JSON.parse(row.permissions), courses: JSON.parse(row.courses), allCourses: !!row.all_courses, password: undefined });
  const can = (user, permission, course) => !!user?.permissions.includes(permission) && (course === undefined || user.allCourses || user.courses.includes(course));
  const requirePermission = (u, p, c) => { if (!can(u, p, c)) fail(403, 'No tiene permiso para esta acción o curso.', 'FORBIDDEN'); };
  const fieldsFor = async id => { const row = await db.prepare('SELECT fields FROM templates WHERE id=?').get(id); return JSON.parse(row?.fields || 'null') || fail(404, 'Plantilla no encontrada.'); };
  const courseFor = async id => await db.prepare('SELECT * FROM courses WHERE id=?').get(id) || fail(404, 'Curso no encontrado.');
  const load = async id => await db.prepare('SELECT * FROM records WHERE id=?').get(id) || fail(404, 'Ficha no encontrada.');
  const getData = row => JSON.parse(unseal(row.data));
  const filtered = (data, fields, u) => Object.fromEntries(Object.entries(data).filter(([k]) => { const f = fields.find(x => x.key === k); return f && (!f.sensitive || can(u, 'sensitive')); }));
  const cleanData = (input, fields, u, initial = {}) => {
    if (!input || typeof input !== 'object' || Array.isArray(input)) fail(400, 'Datos de ficha inválidos.');
    const data = { ...initial }; for (const [k, v] of Object.entries(input)) { const f = fields.find(x => x.key === k); if (!f) fail(400, 'La ficha contiene un campo desconocido.'); if (f.sensitive) requirePermission(u, 'sensitive'); if (typeof v !== 'string' || v.length > (f.type === 'textarea' ? 4000 : 500)) fail(400, 'Valor inválido o demasiado largo.'); if (f.type === 'select' && v && !f.options.includes(v)) fail(400, 'Opción inválida.'); if (f.type === 'date' && v && (!/^\d{4}-\d{2}-\d{2}$/.test(v) || !Number.isFinite(Date.parse(v)) || new Date(v).toISOString().slice(0, 10) !== v)) fail(400, 'Fecha inválida.'); data[k] = v.trim(); }
    if (!data.names || !data.surname) fail(400, 'Indique nombres y apellido paterno.'); if (data.identifierType !== 'Provisional' && !data.identifier) fail(400, 'Indique identificación o seleccione Provisional.'); if (!validateIdentifier(data.identifierType, data.identifier)) fail(400, 'RUN inválido. Revise el dígito verificador.');
    for (const p of ['religion', 'images', 'outings']) { const changed = [p + 'Decision', p + 'Detail', p + 'Date', p + 'Responsible', p + 'Version'].some(k => data[k] !== initial[k]); if (changed && data[p + 'Decision'] && data[p + 'Decision'] !== 'Pendiente' && (!data[p + 'Date'] || !data[p + 'Responsible'] || !data[p + 'Version'])) fail(400, 'Cada autorización requiere fecha, responsable y versión informada.'); }
    return data;
  };
  const identity = data => mac(data.identifierType === 'Provisional' ? 'provisional:' + randomUUID() : (data.identifierType || 'Otro') + ':' + normalizeIdentifier(data.identifier));
  const name = data => `${data.surname} ${data.secondSurname || ''}, ${data.names}`.replace(/\s+/g, ' ').replace(/\s+,/g, ',').trim();
  const revision = async (row, u) => await db.prepare('INSERT INTO revisions(record_id,version,actor,at,snapshot) VALUES(?,?,?,?,?)').run(row.id, row.version, u.id, now(), seal({ year: row.year, courseId: row.course_id, status: row.status, templateId: row.template_id, data: getData(row) }));
  const event = async (id, u, action, detail) => await db.prepare('INSERT INTO events(record_id,action,actor,at,detail) VALUES(?,?,?,?,?)').run(id, action, u.id, now(), seal(detail));
  const versionCheck = (row, version) => { if (!Number.isInteger(version) || row.version !== version) fail(409, 'Otra persona modificó esta ficha. Sus cambios se conservaron en pantalla; recargue y revise antes de guardar.', 'VERSION_CONFLICT'); };
  const publicRecord = async (row, u) => ({ id: row.id, studentId: row.student_id, year: row.year, courseId: row.course_id, templateId: row.template_id, status: row.status, name: row.name, version: row.version, updatedAt: row.updated_at, data: filtered(getData(row), await fieldsFor(row.template_id), u) });
  const list = async (u, query = {}) => {
    requirePermission(u, 'read'); const clauses = [], params = []; if (!u.allCourses) { if (!u.courses.length) return { items: [], total: 0, page: 1, pageSize: 25 }; clauses.push(`course_id IN (${u.courses.map(() => '?').join(',')})`); params.push(...u.courses); } if (query.year) { clauses.push('year=?'); params.push(Number(query.year)); } if (query.course) { requirePermission(u, 'read', query.course); clauses.push('course_id=?'); params.push(query.course); } if (query.status) { clauses.push('status=?'); params.push(query.status); } if (query.q) { clauses.push("(name LIKE ? ESCAPE '\\' OR student_id IN (SELECT id FROM students WHERE identity_hash IN (?, ?, ?, ?)))"); const search = String(query.q).slice(0, 100).replace(/[\\%_]/g, x => '\\' + x); params.push('%' + search + '%', ...['RUN', 'IPE', 'Pasaporte', 'Otro'].map(type => mac(type + ':' + normalizeIdentifier(query.q)))); }
    const page = Math.max(1, Math.floor(Number(query.page) || 1)), pageSize = Math.min(100, Math.max(1, Math.floor(Number(query.pageSize) || 25))), where = clauses.length ? 'WHERE ' + clauses.join(' AND ') : ''; const total = (await db.prepare(`SELECT count(*) AS n FROM records ${where}`).get(...params)).n; const items = await db.prepare(`SELECT id,student_id AS "studentId",year,course_id AS "courseId",status,name,version,updated_at AS "updatedAt" FROM records ${where} ORDER BY name,id LIMIT ? OFFSET ?`).all(...params, pageSize, (page - 1) * pageSize); await audit(u.id, 'records.list', '', { year: query.year || null, course: query.course || null, count: items.length, search: !!query.q }); return { items, total, page, pageSize };
  };
  const detail = async (u, id) => {
    const row = await load(id); requirePermission(u, 'read', row.course_id); const record = await publicRecord(row, u); record.attachments = can(u, 'documents') ? (await db.prepare('SELECT id,kind,name,mime,sensitive,size,at FROM attachments WHERE record_id=? ORDER BY at DESC').all(id)).filter(x => !x.sensitive || can(u, 'sensitive')) : [];
    const eventRows = await db.prepare('SELECT * FROM events WHERE record_id=? ORDER BY id DESC').all(id); record.events = []; for (const x of eventRows) { const actor = await db.prepare('SELECT name FROM users WHERE id=?').get(x.actor); record.events.push({ id: x.id, action: x.action, actor: actor?.name || x.actor, at: x.at, detail: JSON.parse(unseal(x.detail)) }); } record.annualHistory = (await db.prepare('SELECT id,year,course_id AS "courseId",status FROM records WHERE student_id=? ORDER BY year DESC').all(row.student_id)).filter(x => can(u, 'read', x.courseId)); record.revisions = await db.prepare('SELECT version,actor,at FROM revisions WHERE record_id=? ORDER BY version DESC').all(id); record.pending = ['guardianName', 'guardianPhone', 'emergencyPhone', 'imagesDecision', 'outingsDecision', 'birthCertificate'].filter(k => !record.data[k] || record.data[k] === 'Pendiente'); await audit(u.id, 'record.read', id, { version: row.version, sensitive: can(u, 'sensitive') }); return record;
  };
  const create = async (u, input) => { requirePermission(u, 'write', input.courseId); const course = await courseFor(input.courseId); if (course.year !== Number(input.year)) fail(400, 'Curso y año no corresponden.'); const templateRow = input.templateId ? null : await db.prepare('SELECT max(id) AS id FROM templates').get(); const templateId = input.templateId || templateRow.id; const data = cleanData(input.data, await fieldsFor(templateId), u); const hash = identity(data); if (await db.prepare('SELECT id FROM students WHERE identity_hash=?').get(hash)) fail(409, 'Identificación ya registrada. Abra la ficha existente para renovar.', 'DUPLICATE'); return transaction(async () => { const studentId = randomUUID(), id = randomUUID(); await db.prepare('INSERT INTO students(id,identity_hash,origin,origin_id) VALUES(?,?,?,?)').run(studentId, hash, input.origin || null, input.originId || null); await db.prepare('INSERT INTO records VALUES(?,?,?,?,?,?,?,?,?,?)').run(id, studentId, course.year, course.id, templateId, 'draft', name(data), 1, seal(data), now()); const row = await load(id); await revision(row, u); await event(id, u, 'created', {}); await audit(u.id, 'record.create', id, { year: course.year, course: course.id, fields: Object.keys(data) }); return publicRecord(row, u); }); };
  const patch = async (u, id, input) => transaction(async () => { const row = await load(id); requirePermission(u, 'write', row.course_id); versionCheck(row, input.version); if (row.status === 'withdrawn') fail(409, 'Ficha retirada: el historial se conserva sin nuevas ediciones.'); const previous = getData(row), data = cleanData(input.data, await fieldsFor(row.template_id), u, previous), changed = Object.keys(data).filter(k => previous[k] !== data[k]); if (!changed.length) return publicRecord(row, u); if (changed.includes('identifier') || changed.includes('identifierType')) { const hash = identity(data), duplicate = await db.prepare('SELECT id FROM students WHERE identity_hash=?').get(hash); if (duplicate && duplicate.id !== row.student_id) fail(409, 'Identificación ya registrada.', 'DUPLICATE'); await db.prepare('UPDATE students SET identity_hash=? WHERE id=?').run(hash, row.student_id); } await db.prepare('UPDATE records SET name=?,data=?,version=version+1,updated_at=? WHERE id=?').run(name(data), seal(data), now(), id); const updated = await load(id); await revision(updated, u); await audit(u.id, 'record.edit', id, { version: updated.version, changes: changed.map(key => ({ field: key, before: mac(JSON.stringify(previous[key] ?? '')), after: mac(JSON.stringify(data[key])) })) }); return publicRecord(updated, u); });
  const transition = async (u, id, input) => transaction(async () => { const row = await load(id); requirePermission(u, 'enroll', row.course_id); versionCheck(row, input.version); if (row.status === 'withdrawn') fail(409, 'Esta matrícula ya fue retirada.'); let status = row.status, courseId = row.course_id; if (input.action === 'enroll') { if (status !== 'draft') fail(409, 'La matrícula ya está confirmada.'); status = 'enrolled'; } else if (input.action === 'transfer') { const course = await courseFor(input.courseId); requirePermission(u, 'enroll', course.id); if (course.year !== row.year || course.id === row.course_id) fail(400, 'Elija otro curso del mismo año.'); courseId = course.id; } else if (input.action === 'withdraw') status = 'withdrawn'; else fail(400, 'Acción de matrícula desconocida.'); if (input.action !== 'enroll' && (!input.reason || typeof input.reason !== 'string' || input.reason.trim().length < 3 || input.reason.length > 1000)) fail(400, 'Indique un motivo de al menos tres caracteres.'); const date = input.date || now().slice(0, 10); if (!/^\d{4}-\d{2}-\d{2}$/.test(date) || !Number.isFinite(Date.parse(date)) || new Date(date).toISOString().slice(0, 10) !== date) fail(400, 'Fecha de movimiento inválida.'); await db.prepare('UPDATE records SET status=?,course_id=?,version=version+1,updated_at=? WHERE id=?').run(status, courseId, now(), id); await event(id, u, input.action, { fromCourse: row.course_id, toCourse: courseId, date, reason: input.reason || '' }); const updated = await load(id); await revision(updated, u); await audit(u.id, 'enrollment.' + input.action, id, { version: updated.version, fromCourse: row.course_id, toCourse: courseId, date, reasonHash: mac(input.reason || '') }); return publicRecord(updated, u); });
  const renew = async (u, id, input) => transaction(async () => { const row = await load(id); requirePermission(u, 'enroll', row.course_id); versionCheck(row, input.version); const course = await courseFor(input.courseId); requirePermission(u, 'enroll', course.id); if (course.year <= row.year) fail(400, 'La renovación debe corresponder a un año posterior.'); if (row.status === 'withdrawn') fail(409, 'Revise el reingreso de un estudiante retirado antes de renovar.'); if (await db.prepare('SELECT id FROM records WHERE student_id=? AND year=?').get(row.student_id, course.year)) fail(409, 'Ya existe ficha de este estudiante en ese año.', 'DUPLICATE_YEAR'); const data = getData(row); for (const field of await fieldsFor(row.template_id)) if (['matricula', 'constancias', 'documentos', 'autorizaciones', 'retiro'].includes(field.section)) delete data[field.key]; const templateId = (await db.prepare('SELECT max(id) AS id FROM templates').get()).id, newId = randomUUID(); await db.prepare('INSERT INTO records VALUES(?,?,?,?,?,?,?,?,?,?)').run(newId, row.student_id, course.year, course.id, templateId, 'draft', name(data), 1, seal(data), now()); const updated = await load(newId); await revision(updated, u); await event(newId, u, 'renewed', { sourceId: id, sourceYear: row.year }); await audit(u.id, 'enrollment.renew', newId, { source: id, year: course.year, course: course.id }); return publicRecord(updated, u); });
  const createCourse = async (u, input) => { requirePermission(u, 'enroll'); const year = Number(input.year), label = String(input.name || '').trim(); if (!Number.isInteger(year) || year < 2020 || year > 2100 || !label || label.length > 80) fail(400, 'Año o nombre de curso inválido.'); const id = randomUUID(); await db.prepare('INSERT INTO courses VALUES(?,?,?)').run(id, year, label); await audit(u.id, 'course.create', id, { year }); return { id, year, name: label }; };
  const saveUser = async (u, input, id) => transaction(async () => { requirePermission(u, 'admin'); if (!Array.isArray(input.permissions) || input.permissions.some(x => !permissions.includes(x)) || !Array.isArray(input.courses)) fail(400, 'Permisos o cursos inválidos.'); for (const courseId of input.courses) if (!await db.prepare('SELECT id FROM courses WHERE id=?').get(courseId)) fail(400, 'Permisos o cursos inválidos.'); const username = String(input.username || '').trim().toLowerCase(), label = String(input.name || '').trim(); if (!/^[a-z0-9._-]{3,60}$/.test(username) || !label || label.length > 120) fail(400, 'Cuenta o nombre inválido.'); const existing = id ? await db.prepare('SELECT * FROM users WHERE id=?').get(id) : null; if (id && !existing) fail(404, 'Cuenta no encontrada.'); if (id === u.id && (!input.permissions.includes('admin') || input.active === false)) fail(400, 'Conserve acceso administrativo en su propia cuenta.'); if ((!existing || input.password) && (!input.password || input.password.length < 12 || input.password.length > 200)) fail(400, 'La contraseña debe tener entre 12 y 200 caracteres.'); const userId = id || randomUUID(), pass = input.password ? hashPassword(input.password) : existing.password; await db.prepare('INSERT INTO users VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET username=excluded.username,name=excluded.name,password=excluded.password,permissions=excluded.permissions,courses=excluded.courses,all_courses=excluded.all_courses,active=excluded.active').run(userId, username, label, pass, JSON.stringify([...new Set(input.permissions)]), JSON.stringify([...new Set(input.courses)]), input.allCourses ? 1 : 0, input.active === false ? 0 : 1); if (existing) await db.prepare('DELETE FROM sessions WHERE user_id=?').run(userId); await audit(u.id, 'user.configure', userId, { permissions: input.permissions, courses: input.courses, allCourses: !!input.allCourses, active: input.active !== false, passwordChanged: !!input.password }); return decodeUser(await db.prepare('SELECT * FROM users WHERE id=?').get(userId)); });
  const createTemplate = async (u, input) => { requirePermission(u, 'admin'); try { validateFields(input.fields); } catch (e) { fail(400, e.message); } const label = String(input.name || '').trim(); if (!label || label.length > 120) fail(400, 'Nombre de versión inválido.'); const result = await db.prepare('INSERT INTO templates(name,fields,created_at) VALUES(?,?,?)').run(label, JSON.stringify(input.fields), now()); const id = Number(result.lastInsertRowid); await audit(u.id, 'template.create', String(id), { count: input.fields.length }); return { id, name: label }; };
  const addAttachment = async (u, id, input) => { const row = await load(id); requirePermission(u, 'write', row.course_id); requirePermission(u, 'documents'); versionCheck(row, input.version); if (row.status === 'withdrawn') fail(409, 'No puede adjuntar a una matrícula retirada.'); const sensitive = input.kind !== 'identity' || input.sensitive !== false; if (sensitive) requirePermission(u, 'sensitive'); if (!['signed', 'identity', 'support'].includes(input.kind) || typeof input.content !== 'string') fail(400, 'Tipo de documento inválido.'); const bytes = Buffer.from(input.content, 'base64'); if (!bytes.length || bytes.length > (store.maxAttachmentBytes || 5 * 1024 * 1024)) fail(400, 'Adjunte un archivo de hasta 5 MB.'); const mime = bytes.subarray(0, 5).toString() === '%PDF-' ? 'application/pdf' : bytes.subarray(0, 8).equals(Buffer.from([137, 80, 78, 71, 13, 10, 26, 10])) ? 'image/png' : bytes.subarray(0, 3).equals(Buffer.from([255, 216, 255])) ? 'image/jpeg' : null; if (!mime) fail(400, 'Se aceptan PDF, PNG o JPEG con formato válido.'); const filename = String(input.name || 'documento').replace(/[\\/\x00-\x1f]/g, '_').slice(0, 150), attachmentId = randomUUID(); await store.files.write(attachmentId, seal(bytes.toString('base64'))); try { return await transaction(async () => { await db.prepare('INSERT INTO attachments VALUES(?,?,?,?,?,?,?,?,?,?)').run(attachmentId, id, input.kind, filename, mime, sensitive ? 1 : 0, mac(bytes), bytes.length, u.id, now()); await db.prepare('UPDATE records SET version=version+1,updated_at=? WHERE id=?').run(now(), id); await revision(await load(id), u); await event(id, u, 'document.add', { attachmentId, kind: input.kind }); await audit(u.id, 'document.upload', id, { attachmentId, kind: input.kind, size: bytes.length, sensitive }); return { id: attachmentId, version: (await load(id)).version }; }); } catch (e) { await store.files.remove(attachmentId).catch(() => {}); throw e; } };
  const downloadAttachment = async (u, id) => { const attachment = await db.prepare('SELECT * FROM attachments WHERE id=?').get(id) || fail(404, 'Documento no encontrado.'); const record = await load(attachment.record_id); requirePermission(u, 'read', record.course_id); requirePermission(u, 'documents'); if (attachment.sensitive) requirePermission(u, 'sensitive'); const bytes = Buffer.from(unseal(await store.files.read(id)), 'base64'); if (mac(bytes) !== attachment.hash) fail(500, 'El documento no superó la verificación de integridad.'); await audit(u.id, 'document.download', record.id, { attachmentId: id }); return { ...attachment, bytes }; };
  const importPreview = async (u, input) => { requirePermission(u, 'import'); requirePermission(u, 'write'); if (!Array.isArray(input.rows) || input.rows.length > 500) fail(400, 'Use hasta 500 filas.'); const seen = new Set(), templateId = (await db.prepare('SELECT max(id) AS id FROM templates').get()).id, rows = []; for (let i = 0; i < input.rows.length; i++) { const r = input.rows[i]; let issue = ''; try { const course = await courseFor(r.courseId); requirePermission(u, 'write', course.id); if (course.year !== Number(r.year)) fail(400, 'Curso y año no corresponden.'); cleanData(r.data, await fieldsFor(templateId), u); if (r.data.identifierType === 'Provisional') fail(400, 'Importación requiere identificador de origen e identidad verificable.'); if (!r.origin || !r.originId || typeof r.origin !== 'string' || typeof r.originId !== 'string' || r.origin.length > 100 || r.originId.length > 100) fail(400, 'Indique procedencia e identificador de origen.'); const hash = identity(r.data), origin = r.origin + ':' + r.originId; if (seen.has(hash) || seen.has(origin) || await db.prepare('SELECT id FROM students WHERE identity_hash=? OR (origin=? AND origin_id=?)').get(hash, r.origin, r.originId)) issue = 'Duplicado'; seen.add(hash); seen.add(origin); } catch (e) { issue = e.message; } rows.push({ index: i, name: r.data?.names || '', issue }); } await audit(u.id, 'import.preview', '', { count: rows.length, issues: rows.filter(x => x.issue).length }); const ticket = mac(JSON.stringify(input.rows)); return { rows, ticket, canImport: !rows.some(x => x.issue) }; };
  const importCommit = async (u, input) => { requirePermission(u, 'import'); const preview = await importPreview(u, input); if (input.ticket !== preview.ticket || !preview.canImport) fail(409, 'Revise la previsualización y resuelva duplicados.'); return transaction(async () => { const ids = []; for (const r of input.rows) { const course = await courseFor(r.courseId), templateId = (await db.prepare('SELECT max(id) AS id FROM templates').get()).id, data = cleanData(r.data, await fieldsFor(templateId), u), studentId = randomUUID(), id = randomUUID(); await db.prepare('INSERT INTO students VALUES(?,?,?,?)').run(studentId, identity(data), r.origin, r.originId); await db.prepare('INSERT INTO records VALUES(?,?,?,?,?,?,?,?,?,?)').run(id, studentId, course.year, course.id, templateId, 'draft', name(data), 1, seal(data), now()); await revision(await load(id), u); await event(id, u, 'imported', { origin: r.origin, originId: r.originId }); ids.push(id); } await audit(u.id, 'import.commit', '', { count: ids.length }); return { count: ids.length, ids }; }); };
  return { can, requirePermission, decodeUser, fieldsFor, courseFor, load, getData, filtered, list, detail, create, patch, transition, renew, createCourse, saveUser, createTemplate, addAttachment, downloadAttachment, importPreview, importCommit };
}
