-- Matrícula independiente · PostgreSQL/Supabase
-- Esta migración se ejecuta explícitamente (Supabase CLI o revisión SQL).
-- La aplicación no aplica DDL al arrancar una función de Vercel.

create schema if not exists matricula;

create table if not exists matricula.users (
  id text primary key,
  username text unique not null,
  name text not null,
  password text not null,
  permissions text not null,
  courses text not null,
  all_courses smallint not null default 0 check (all_courses in (0, 1)),
  active smallint not null default 1 check (active in (0, 1))
);

create table if not exists matricula.sessions (
  token_hash text primary key,
  user_id text not null references matricula.users(id),
  csrf text not null,
  expires bigint not null
);

create table if not exists matricula.courses (
  id text primary key,
  year integer not null,
  name text not null,
  unique (year, name)
);

create table if not exists matricula.templates (
  id integer generated by default as identity primary key,
  name text not null,
  fields text not null,
  created_at text not null
);

create table if not exists matricula.students (
  id text primary key,
  identity_hash text unique not null,
  origin text,
  origin_id text,
  unique (origin, origin_id)
);

create table if not exists matricula.records (
  id text primary key,
  student_id text not null references matricula.students(id),
  year integer not null,
  course_id text not null references matricula.courses(id),
  template_id integer not null references matricula.templates(id),
  status text not null check (status in ('draft', 'enrolled', 'withdrawn')),
  name text not null,
  version integer not null,
  data text not null,
  updated_at text not null,
  unique (student_id, year)
);

create index if not exists record_lookup on matricula.records(year, course_id, status, name);

create table if not exists matricula.revisions (
  id integer generated by default as identity primary key,
  record_id text not null references matricula.records(id),
  version integer not null,
  actor text not null,
  at text not null,
  snapshot text not null,
  unique (record_id, version)
);

create table if not exists matricula.events (
  id integer generated by default as identity primary key,
  record_id text not null references matricula.records(id),
  action text not null,
  actor text not null,
  at text not null,
  detail text not null
);

create table if not exists matricula.attachments (
  id text primary key,
  record_id text not null references matricula.records(id),
  kind text not null,
  name text not null,
  mime text not null,
  sensitive smallint not null check (sensitive in (0, 1)),
  hash text not null,
  size integer not null,
  actor text not null,
  at text not null
);

-- Encrypted attachment blobs stay in this private schema. There is purposely
-- no FK to attachments: the blob is written before the metadata transaction;
-- failed metadata transactions remove the orphan blob in application code.
create table if not exists matricula.attachment_blobs (
  id text primary key,
  content text not null,
  created_at text not null
);

create table if not exists matricula.audit (
  id integer generated by default as identity primary key,
  actor text not null,
  at text not null,
  action text not null,
  target text not null,
  detail text not null,
  prev_hash text not null,
  hash text not null
);

-- Persistent login throttling replaces the process-local Map used by SQLite.
create table if not exists matricula.login_attempts (
  ip_hash text primary key,
  count integer not null default 0,
  window_started bigint not null,
  blocked_until bigint not null default 0
);

create index if not exists sessions_expiry on matricula.sessions(expires);
create index if not exists audit_order on matricula.audit(id);
create index if not exists blob_created on matricula.attachment_blobs(created_at);

create or replace function matricula.reject_immutable_row()
returns trigger
language plpgsql
security invoker
set search_path = pg_catalog, matricula
as $$
begin
  raise exception '% es inmutable: no se permite %', tg_table_name, tg_op
    using errcode = '42501';
end;
$$;

drop trigger if exists audit_no_update on matricula.audit;
create trigger audit_no_update before update or delete on matricula.audit
for each row execute function matricula.reject_immutable_row();

drop trigger if exists revisions_no_update on matricula.revisions;
create trigger revisions_no_update before update or delete on matricula.revisions
for each row execute function matricula.reject_immutable_row();

drop trigger if exists events_no_update on matricula.events;
create trigger events_no_update before update or delete on matricula.events
for each row execute function matricula.reject_immutable_row();

drop trigger if exists templates_no_update on matricula.templates;
create trigger templates_no_update before update or delete on matricula.templates
for each row execute function matricula.reject_immutable_row();

-- RLS denies browser-facing Supabase roles by default because there are no
-- policies. The Vercel server connects with the database URL/service role.
do $$
declare
  table_name text;
begin
  foreach table_name in array array['users','sessions','courses','templates','students','records','revisions','events','attachments','attachment_blobs','audit','login_attempts'] loop
    execute format('alter table matricula.%I enable row level security', table_name);
    if exists (select 1 from pg_roles where rolname = 'anon') then
      execute format('revoke all on matricula.%I from anon', table_name);
    end if;
    if exists (select 1 from pg_roles where rolname = 'authenticated') then
      execute format('revoke all on matricula.%I from authenticated', table_name);
    end if;
    execute format('revoke all on matricula.%I from public', table_name);
    if exists (select 1 from pg_roles where rolname = 'service_role') then
      execute format('grant select, insert, update, delete, references on matricula.%I to service_role', table_name);
    end if;
  end loop;
  execute 'revoke all on schema matricula from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then execute 'revoke all on schema matricula from anon'; end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then execute 'revoke all on schema matricula from authenticated'; end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then execute 'grant usage on schema matricula to service_role'; end if;
end;
$$;

do $$
begin
  execute 'revoke all on all sequences in schema matricula from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then execute 'revoke all on all sequences in schema matricula from anon'; end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then execute 'revoke all on all sequences in schema matricula from authenticated'; end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant usage, select on all sequences in schema matricula to service_role';
  end if;
end;
$$;
